### PR TITLE
Supports per application environment variables. Fixes #21

### LINKED ISSUE #21: Allow setting environment variables
I suppose we can do:

```
application "blah" {

  env {
    ES_HOME  = /usr/share/elasticsearch
    CONF_DIR = /etc/elasticsearch
    DATA_DIR = /var/lib/elasticsearch
    LOG_DIR  = /var/log/elasticsearch
    PID_DIR  = /var/run/elasticsearch
  }

  env_file = "blah.env"
}

```

### PR DESCRIPTION
**Pull request by drystone**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@drystone I believe the environment variables would be better set in this way rather than in an array?

```
application "xxx" {
  env {
    FOOBAR = "foo"
    BARFOO = "bar"
  }
}
```

**Comment by drystone** [comment]
Is there a compelling reason to use a dictionary?

To pass a variable (`NEREON_FILESET`) through from riffol's environment the current (array) syntax is
```
application "xxx" {
    env = [
        NEREON_FILESET
        LD_LIBRARY_PATH=/usr/local/lib
    ]
}
```
Using a dictionary would require a value for `NEREON_FILESET`.

**Comment by ronaldtse** [comment]
Environment variables have a unique key, so a dictionary would be most suitable?

**Comment by drystone** [comment]
Is it worth the additional syntax to pass the environment variable through from riffol?
```
env  = {
    NEREON_FILESET = "$NEREON_FILESET"
}
```
In which case should we allow arbitrary substitution, not just at the beginning of the string?
```
env = {
    PATH = /usr/local/bin:$PATH
}
```
and escaping?
```
CURRENCY="\$"
```
?

**Comment by ronaldtse** [comment]
This is a great idea -- the only uncertainty to me is about interpolation, whether this:

```
    PATH = /usr/local/bin:$PATH
```

should look like this:
```
    PATH = "/usr/local/bin:${PATH}"
```

or something like:
```
    PATH = "/usr/local/bin:${env.PATH}"
```

**Pull request merged**
