### PR TITLE
Prepare for crates.io upload

### PR DESCRIPTION
**Pull request by drystone**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@drystone could we update the author to add our riboseinc caela team as owner as well? Thanks!

**Comment by drystone** [comment]
Sure, what's the email address?

**Comment by ronaldtse** [comment]
If you add “open.source@ribose.com” I can handle the rest :wink:

**Comment by ronaldtse** [comment]
I’ve also got a question about strings and variables. 

We now have:
* exec "/riffol/openvpn-init.sh"
* exec nereond 

How are they different?

**Comment by drystone** [comment]
Thanks, I'll amend authors for all crates.

Unquoted strings can contain any alphanumeric and `_`. Other strings need quoting otherwise the parser will fail. For example it will treat an unquoted '-' as the subtraction operator.

**Pull request merged**
