### PR TITLE
OpenVPN example

### LINKED ISSUE #10: Riffol example: OpenVPN docker container
We want to manage OpenVPN within a docker container.

This involves:

* Riffol needs to take in a configuration that allows configuring OpenVPN (private key, CA public key, CA certificate)
* This configuration can be read in via a Base64-serialized data structure through an environment variable via Docker
* The structure of the serialized configuration should be in NON syntax (i.e. UCL, for now). At this stage, we just need to directly write the configuration files' content without using Nereon to generate them.

e.g. (all this content gets serialized in Base64 to docker which passes it to Riffol)
```hcl
group "openvpn" {
  name = "openvpn"
}

user "openvpn" {
  name = "openvpn"
  group = "${group.openvpn.name}"
}

file "openvpn-main-config" {
  path = "/etc/openvpn/openvpn.conf"
  mode = "0400"
  user = "${user.openvpn.name}"
  group = "${group.openvpn.name}"
  // Full config from https://github.com/OpenVPN/openvpn/blob/master/sample/sample-config-files/server.conf
  content = <<EOF
proto udp
dev tun
dh dh2048.pem
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
keepalive 10 120
tls-auth ta.key 0 # This file is secret
cipher AES-256-CBC
persist-key
persist-tun
status openvpn-status.log
verb 3
explicit-exit-notify 1
EOF
  write_on_start = true
}

file "openvpn-ca-cert" {
  path = "/etc/openvpn/ca.crt"
  mode = "0400"
  user = "${user.openvpn.name}"
  group = "${group.openvpn.name}"
  content = <<EOF
===== BEGIN RSA KEY =====
...
EOF
}

file "openvpn-server-cert" {
  path = "/etc/openvpn/server.crt"
  mode = "0400"
  user = "${user.openvpn.name}"
  group = "${group.openvpn.name}"
  content = <<EOF
===== BEGIN RSA KEY =====
...
EOF
}

file "openvpn-server-key" {
  path = "/etc/openvpn/server.key"
  mode = "0400"
  user = "${user.openvpn.name}"
  group = "${group.openvpn.name}"
  content = <<EOF
===== BEGIN RSA KEY =====
...
EOF
}
```

Once Riffol gets the configuration, it writes the configuration to disk and starts OpenVPN. 

This example should support restarting the OpenVPN process if it dies (without having the main process (Riffol) quit, which will kill the container itself).

So we need to create a repo for this OpenVPN docker container first.

UPDATED: added `mode`, `user` and `group` as well as the definition of user and group.

### PR DESCRIPTION
**Pull request by drystone**
Simple OpenVPN example using Nereond and static configuration. Fixes #10

### CODE REVIEW

**Comment by drystone** [comment]
@ronaldtse, @erikbor please check over the example to make sure this is heading in the right direction. You may also want to have a look at https://github.com/riboseinc/nereond.git

Once you are satisfied, I'll populate the riffol-OpenVPN repository with the contents of /examples/{openvpn.sh,openvpn} and add a README

Cheers

**Comment by ronaldtse** [comment]
@drystone this looks really good. However the updated `server.crt` is missing the actual certificate in Base64, namely the line that starts with `MIIDXTCCAkWgAwIBAgIRANYL6yc3b5gHjLuseAntbZ0wDQYJKoZIhvcNAQELBQAw`?

**Comment by ronaldtse** [comment]
Could you also help add a `.travis.yml` so that Travis can build this as a test? Thanks!

**Comment by ronaldtse** [comment]
@drystone feel free to merge when ready. Thanks!

**Pull request merged**
